services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: diogolemos
      POSTGRES_PASSWORD: Odysseus
      POSTGRES_DB: Odysseus
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://diogolemos:Odysseus@postgres:5432/Odysseus

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NUXT_UI_PRO_LICENSE: "BB9C17E6-CD38-44FD-B804-441CA336D608"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata: