services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: diogolemos
      POSTGRES_PASSWORD: vaporeon
      POSTGRES_DB: vaporeon
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  djangographql:
    build: 
      context: ./djangographql
      dockerfile: Dockerfile
    container_name: djangographql
    depends_on:
      - postgres
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: "postgresql://diogolemos:vaporeon@postgres:5432/vaporeon"
      POSTGRES_DB: vaporeon
      POSTGRES_USER: diogolemos
      POSTGRES_PASSWORD: vaporeon
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - ./djangographql:/app
    restart: always
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_api
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgres://diogolemos:vaporeon@postgres:5432/vaporeon"
    restart: always

  laravelgraphql:
    build:
      context: ./laravel-graphql
      dockerfile: Dockerfile
    container_name: laravelgraphql
    depends_on:
      - postgres
    ports:
      - "8002:8002"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: vaporeon
      DB_USERNAME: diogolemos
      DB_PASSWORD: vaporeon
    volumes:
      - ./laravel-graphql:/app
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NUXT_UI_PRO_LICENSE: ${NUXT_UI_PRO_LICENSE}
    container_name: frontend_app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

volumes:
  pgdata: